name: '${name}'
version: '${version}'
main: '${main}'

commands:
  set-up-streamer:
    description: Main command for StreamersUnite
    permission: streamersunite.command.set-up-streamer
    aliases: []
  go-live:
    description: Command to set yourself as live
    permission: streamersunite.command.go-live
    aliases:
      - on
      - online
      - live
      - glive
      - golive
  go-offline:
    description: Command to set yourself as offline
    permission: streamersunite.command.offline
    aliases:
      - off
      - unlive
      - goff
      - offline
      - gooffline
  livenow:
    description: Command to see who is live
    permission: streamersunite.command.livenow
    aliases:
      - lnow
      - currentlylive
      - checklive
      - whoislive
      - whoslive
      - livern
      - lrn
  broadcast-live:
    description: Command to broadcast that you are live
    permission: streamersunite.command.broadcast-live
    aliases:
      - bclive
      - broadcastlive
      - bl